# SPDX-FileCopyrightText: 2019 Tuomas Siipola
# SPDX-License-Identifier: AGPL-3.0-or-later

language: rust
dist: bionic
services:
  - docker
addons:
  apt:
    packages:
      - musl-tools
install:
  - rustup target add x86_64-unknown-linux-musl
  - rustup component add clippy rustfmt
  - docker pull fsfe/reuse:latest
script:
  - cargo build --release --target=x86_64-unknown-linux-musl
  - cargo clippy
  - cargo fmt --all -- --check
  - docker run --name reuse -v ${TRAVIS_BUILD_DIR}:/repo fsfe/reuse /bin/sh -c "cd /repo; reuse lint"
before_deploy:
  - mv target/x86_64-unknown-linux-musl/release/pio pio-${TRAVIS_TAG}-x86_64-unknown-linux-musl
deploy:
  provider: releases
  api_key: ${GITHUB_TOKEN}
  file: pio-${TRAVIS_TAG}-x86_64-unknown-linux-musl
  skip_cleanup: true
  on:
    tags: true
